In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.shape

(891, 15)

In [4]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [5]:
df.dropna(inplace=True)

In [6]:
df['pclass'].unique()

array([1, 3, 2], dtype=int64)

In [7]:
df['pclass'].value_counts()

1    157
2     15
3     10
Name: pclass, dtype: int64

In [8]:
df['sex'].unique()

array(['female', 'male'], dtype=object)

In [9]:
df['sex'].value_counts()

male      94
female    88
Name: sex, dtype: int64

# Data Pre-processing

In [10]:
x=df[['pclass','sex','age']]

In [11]:
from sklearn import preprocessing
lb=preprocessing.LabelBinarizer()

In [12]:
x['sex']=lb.fit_transform(x['sex'])

C:\Users\Asus\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [13]:
x.head()

pclass  sex   age
1        1    0  38.0
3        1    0  35.0
6        1    1  54.0
10       3    0   4.0
11       1    0  58.0

In [14]:
x.shape

(182, 3)

In [15]:
x.describe()

pclass         sex         age
count  182.000000  182.000000  182.000000
mean     1.192308    0.516484   35.623187
std      0.516411    0.501107   15.671615
min      1.000000    0.000000    0.920000
25%      1.000000    0.000000   24.000000
50%      1.000000    1.000000   36.000000
75%      1.000000    1.000000   47.750000
max      3.000000    1.000000   80.000000

In [16]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 182 entries, 1 to 889
Data columns (total 3 columns):
pclass    182 non-null int64
sex       182 non-null int32
age       182 non-null float64
dtypes: float64(1), int32(1), int64(1)
memory usage: 5.0 KB


In [17]:
y=df['survived']

In [18]:
y.value_counts()


1    123
0     59
Name: survived, dtype: int64

# Fit Model(DecisionTreeClassifier)
# BaggingClassifier

In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

# accuracy score

In [22]:
clf=DecisionTreeClassifier(random_state=42)

In [23]:
clf.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=42,
            splitter='best')

In [24]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [25]:
accuracy_score(y_test,clf.predict(x_test))

0.7213114754098361

In [26]:
confusion_matrix(y_test,clf.predict(x_test))

array([[14, 10],
       [ 7, 30]], dtype=int64)

In [27]:
print(classification_report(y_test,clf.predict(x_test)))

              precision    recall  f1-score   support

           0       0.67      0.58      0.62        24
           1       0.75      0.81      0.78        37

   micro avg       0.72      0.72      0.72        61
   macro avg       0.71      0.70      0.70        61
weighted avg       0.72      0.72      0.72        61



# Random Forest(BaggingClassifier)

In [28]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

# accuracy score(Random Forest)

In [31]:
rf_clf=RandomForestClassifier(random_state=42)


In [32]:
rf_clf.fit(x_train,y_train)

C:\Users\Asus\Anaconda2\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [33]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [34]:
accuracy_score(y_test,clf.predict(x_test))

0.7213114754098361

In [35]:
confusion_matrix(y_test,clf.predict(x_test))

array([[14, 10],
       [ 7, 30]], dtype=int64)

In [36]:
print(classification_report(y_test,clf.predict(x_test)))

              precision    recall  f1-score   support

           0       0.67      0.58      0.62        24
           1       0.75      0.81      0.78        37

   micro avg       0.72      0.72      0.72        61
   macro avg       0.71      0.70      0.70        61
weighted avg       0.72      0.72      0.72        61



# Extra-Tree(Extremely Randomized Trees )


 = Random Forest is build upon Decision Tree
 = Decision Tree node splitting is based on gini or entropy or some other algorithms
 = Extra-Trees make use of random thresholds for each feature unlike Decision Tree

In [48]:
from sklearn.ensemble import ExtraTreesClassifier

In [44]:
xt_clf=ExtraTreesClassifier(random_state=42)

In [45]:
xt_clf.fit(x_train,y_train)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=42, verbose=0, warm_start=False)

In [46]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [47]:
accuracy_score(y_test,clf.predict(x_test))

0.7213114754098361

# Boosting(Hypothesis Boosting)

=COMBINE SEVERAL WEAK LEARNERS INTO A STRONG LEARNER.
=TRAIN PREDICTORS SEQUENTIALLY

# AdaBoost/Adaptive Boosting

In [49]:
from sklearn.ensemble import AdaBoostClassifier
xt_clf=AdaBoostClassifier()
xt_clf.fit(x_train,y_train)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(y_test,clf.predict(x_test))


0.7213114754098361

# AdaBoost with Random Forest

In [50]:
from sklearn.ensemble import RandomForestClassifier
xt_clf=RandomForestClassifier()
xt_clf.fit(x_train,y_train)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(y_test,clf.predict(x_test))

0.7213114754098361

# Gradient Boosting

In [52]:
from sklearn.ensemble import GradientBoostingClassifier
xt_clf=GradientBoostingClassifier()
xt_clf.fit(x_train,y_train)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(y_test,clf.predict(x_test))

0.7213114754098361

# XGBoost

In [57]:
import xgboost as xgb

In [59]:
xgb_clf=xgb.XGBClassifier(max_depth=5,n_estimators=1000,learning_rate=0.3,n_jobs=-1)

In [60]:


xt_clf.fit(x_train,y_train)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(y_test,clf.predict(x_test))

0.7213114754098361