In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv("buildingprice.csv")

In [5]:
df

area  bedrooms  age    price
0   2500         2   10  2000000
1   3000         3   20  1230000
2   3500         4    8  2000000
3   4000         4    3  3500000
4   4500         3    5  2500000
5   5000         4    7  1200000
6   5500         2   21  1340000
7   6000         4   23  1290000
8   6500         3   35  1200000
9   7000         4   28  1800000
10  7500         3   21  1800000

In [8]:
x = df [["area", "bedrooms", "age"]]

In [7]:
x

area  bedrooms  age
0   2500         2   10
1   3000         3   20
2   3500         4    8
3   4000         4    3
4   4500         3    5
5   5000         4    7
6   5500         2   21
7   6000         4   23
8   6500         3   35
9   7000         4   28
10  7500         3   21

In [9]:
y = df[["price"]]

In [10]:
y

price
0   2000000
1   1230000
2   2000000
3   3500000
4   2500000
5   1200000
6   1340000
7   1290000
8   1200000
9   1800000
10  1800000

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [14]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [15]:
lr.fit(x_train, y_train)

LinearRegression()

In [16]:
pre=lr.predict(x_train)

In [17]:
fit = lr.fit(x_train, y_train)

In [19]:
fit.score(x_train, y_train)

0.7841015087118294

In [20]:
lr.predict([[2600, 3, 10]])

C:\Users\imrkm\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[1877140.66401854]])

In [21]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [22]:
model = sm.OLS(y, x)

In [24]:
lr = model.fit()

In [26]:
lr.summary()

C:\Users\imrkm\anaconda3\Lib\site-packages\scipy\stats\_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=11
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  price   R-squared (uncentered):                   0.886
Model:                            OLS   Adj. R-squared (uncentered):              0.843
Method:                 Least Squares   F-statistic:                              20.69
Date:                Thu, 30 May 2024   Prob (F-statistic):                    0.000398
Time:                        19:12:05   Log-Likelihood:                         -162.86
No. Observations:                  11   AIC:                                      331.7
Df Residuals:                       8   BIC:                                      332.9
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
area         159.9690    201.088      0.796      0.449    -303.742     623.680
bedrooms    4.896e+05   2.18e+05      2.246      0.055   -1.31e+04    9.92e+05
age         -4.11e+04   3.19e+04     -1.287      0.234   -1.15e+05    3.25e+04
==============================================================================
Omnibus:                        0.805   Durbin-Watson:                   2.205
Prob(Omnibus):                  0.669   Jarque-Bera (JB):                0.284
Skew:                          -0.378   Prob(JB):                        0.867
Kurtosis:                       2.781   Cond. No.                     4.97e+03
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 4.97e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [31]:
reg = linear_model.LinearRegression()
reg.fit(df[["area", "bedrooms", "age"]],df.price)

LinearRegression()

In [32]:
reg.coef_

array([    82.28308269,  40160.18269987, -51010.58241839])

In [34]:
reg.intercept_

2101961.753846674

In [36]:
reg.predict([(3000, 4, 15)])

C:\Users\imrkm\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1744292.99645501])